### ISSUE TITLE
datasource.loading

### ISSUE THREAD

**Issue by eric-basley** [redpelicans/timetrack#5]
const ClientDataSource = {
  doFetch: {
    remote(state) {
      return new Promise( (resolve, reject) => {
        setTimeout( () => {
          resolve(mockClients);
        }, 100 );
      });
    },

```
local(state) {
  return state.clients.length ? state.clients : null;
},

// BUG: Uncaught Error: Invariant Violation: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch. 
//loading: ClientActions.loading,
success: ClientActions.loaded,
error: ClientActions.fetchFailed
```

  }
};

**Comment by nicolas-briemant** [comment]
Alt datasource seems to work nicely, so the buy might be link with transitionTo of react-router (not sure).
I found a workaround by using defer method which wraps the action in a timeout of 0 second and defer its execution to the next cycle:

``` javascript
loading: ClientActions.loading.defer()
```
